### ISSUE TITLE
Make the module into a package with a __main__.py

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#19]
You can make the digisec module into a package by adding a ```__main__.py```

Then you can run digisec just by running ```python3 -m digisec```
like many Python packages. At the same time you can squelch the Python
error tracebacks for expected errors, and print the traceback for unexpected errors.

```
# -*- mode: python; py-indent-offset: 4; coding: utf-8 -*-

import sys
import traceback

import rsa
from ecdsa import BadSignatureError

from .scripts import main

def imain():
    try:
        i = main()
    except KeyboardInterrupt:
        i = 0
    except (BadSignatureError, rsa.pkcs1.VerificationError) as e:
        # these errors are expected so don't print a traceback
        print(f"SignatureError: {e}")
        i = 2
    except Exception as e:
        # these errors are unexpected
        # OSError: [Errno 98] Address already in use
        # comm.py, line 14, in send_recv        
        print(f"Error: {e}")
        print(traceback.format_exc())
        i = 1
    return i
        
if __name__ == '__main__':
    sys.exit(imain())
```

Also all python file are expected to start with a coding line to declare their encoding
https://peps.python.org/pep-0263/ The one I used adds info for emacs and other editors.

**Comment by emdee-is** [comment]
I think you also want to let ```socket.timeout``` errors come up to this level too. Just printing the error as a timeout message doesn't help much because it forces the user to parse your stdout. Letting the error come up as socket.timeout lets them special case the except to - for example - increase the timeout and retry. socket.timeout is an example of a "soft" error rather than say ```BadSignature```.

**Comment by metebalci** [comment]
(please do not write multiple unrelated topics into a single issue, it makes it very hard to track)

I started this code when I had less python practical experience so there are some side-effects of this.
I can add the support to run as python module but not sure what would be the benefit of it since digsec cannot be used as a module -I think-, it needs probably a good refactor to be able to be embeded into another code.
I still do not agree 100% with catching errors like this. Like I mentioned, BadSignature is handled internally, if this is raised at this point, it can be a bug. I prefer to let user to see full error and report it as it is. However, I will take a look into a few things.
I will check file headers. #23 
About timeout, what you are saying is to embed digsec to another code, which is not the design of the project at the moment like I mentioned above. So if this is tried, workarounds would be needed if possible.

**Comment by emdee-is** [comment]
You're confusing package and module in Python.

What I wrote for ```__main__.py``` turns the existing ```digsec``` module into a package.

It's also the modern way of making a module with a single command line script into a package that can run the script. ```pip``` is an example of this.

digsec is a module as it is in a directory with an ```__init__.py```. All of your
```import digsec.*``` are imports from the Python module called ```digsec```.

The only refactor the code it needs to be called from other code, including your own
```scripts/validate.py``` is to change main() in scripts.py to take a single argument, a list, and have the caller from ```if __name__ == '__main__'``` call ```main(sys.argv[1:])```.
That's all. Then you can use the '+timeout=' as an element of the list you call ```main``` with.

There's really nothing to it.

**Comment by metebalci** [comment]
I understand, what I mean is it does not bring any particular benefit. It even implies you should know how to run it with python -m. At the moment only thing needed is an install with pip like a normal package manager in linux, and then using the command line directly. But I dont see anything negative about it as well, so I will add (I dont mean the error handling).

**Comment by emdee-is** [comment]
It's traditional to check with the originator for their concurrence before closing bugs.

You still need to refactor scripts.py main() to get the sys.argv out of the code and up into ```___main___.py''' so that scripts:main can be called by, for example, ```validate.py```.

**Comment by metebalci** [comment]
This is not a bug, and even if it is, the issue is reopened if it still exists.

I wont change that.
