### ISSUE TITLE
Not all domains have TXT 

### ISSUE THREAD

**Issue by emdee-is** [metebalci/digsec#4]
Your code is great and is just what I need, but a little basic documentation would help people like me who have never used DNSSEC. Some more explanation in the ```validate_second_level_domain.sh``` script of the steps, and the importance of the order of the sequence of steps, would help a lot.

The script is a sequence of steps so it would be nice to make sure the sequence is in strictly required order: maybe it is as I don't know DNSSEC, but the least 2 validations seem to me should come earlier.

If it's in strict order, you can add a ```set -e``` at the top of the file to make it exit on first error.

But if rr=TXT then many domains have no TXT and the script fails in validating with ```Error: file does not exist: ``` so   you could check the existence of the files in bash and gracefully exit in the case of TXT (and any other cases that it's not required),

Also in the case of TXT, it's the one case where you want to see the text, so could your script special case TXT at least and give the user-friendly rendition of the contents? There's no documentation to tell me how to do that.

**Comment by metebalci** [comment]
Thanks for the feedback. 

I do not think if someone never used DNSSEC before, they can use this tool. There is definitely a need of some background knowledge. This tool is very raw, in the sense it even does not add any flag like recursive desired, so the user must know how DNS/DNSSEC works, at least on paper. There is no such documentation here because I refer to my blog post for use of [digsec](https://metebalci.com/blog/a-minimum-complete-tutorial-of-dnssec/) and if a little bit more basic information about DNS/DNSSEC is needed, there is also another [blog post](https://metebalci.com/blog/a-short-practical-tutorial-of-dig-dns-and-dnssec/) which I link from the digsec post. Having said that, I think maybe just a little bit information here might be helpful, including maybe some comments in the validate script. I will see what I can add.

The point of the validate script is also not to say it is definitely a right way to work with DNSSEC, it is not meant to show how a DNSSEC validating resolver should work, it is just an example of how digsec can be used and I also use it as a test script. I will add "set -e", that is useful anyway.

I am not sure what you mean by rr=TXT paragraph, if there is no TXT, naturally you cannot validate anything about it. Again the script is not meant to be used as a tool to validate a chain, the user of digsec should write this according to their need.

I do not think digsec support TXT records by the way, I should add this.

**Comment by emdee-is** [comment]
> I do not think if someone never used DNSSEC before, they can use this tool. 

You're wrong - I did!!! And for a real use case - getting real world TXT by DNSsec.

The sequence of steps does not validate in strict order to me; I'd validate . and .com before I tried to validate ```metebalci.com```

In my rr=TXT paragraph I meant that if there is no TXT, your script fails on a filenotfound instead of naturally using bash to not do anything about it if it's not there, only in the case of TXT.

Have you tried your script on ```metebalci.com```? I fail to validate (the DBUG and EROR are my debugging additions):
```

DBUG: validating metebalci.com TXT with metebalci.com DNSKEY
ERROR in RRSIG (TXT, ECDSAP256SHA256) Validation ! Signature Mismatch
EROR: 1 validating metebalci.com TXT with metebalci.com DNSKEY
```

If you included a copy of the biog posts as html in the distribution that would help. Your site is behind a cloudflare firewall and cannot be accessed by people using tor.

**Comment by metebalci** [comment]
Getting a TXT record is a job of DNS. DNSSEC validates if this record is authenticated. 

I am sure there are more user friendly tools for what you want to do, you might want to google.

This tool is not a validating DNSSEC resolver. It is only a helper for reading and validating single DNSSEC record, because it is hard to see what is going on.

The point of this project is the digsec tool, not a bash script. You can write a better bash script for your usecase.

I did not test the tool with TXT records. As I told above, I do not think at the moment TXT is supported. If you run `digsec query metebalci.com A +rd` it returns an answer, but `digsec query metebalci.com TXT +rd` does not return an answer where it should. So it is not going to work with TXT anyway without adding a support for it. The validate script works with metebalci.com and A records, not with TXT records because of this.

No I will not add the blog post to the project.

**Comment by emdee-is** [comment]
I think you may be  mistaken: your code does fetch TXT and at the moment TXT is supported. It returned an answer for me: does your ```google-site-verification``` start with ```DrJqf5AW6oDGWp```?

You are mistaken, and your site is behind a cloudflare firewall for 2,500,000 users that are very interested in DNSsec because they use DNSsec TXT records to propagate verification info: https://metrics.torproject.org/userstats-relay-country.html

That may be your cloudflare settings.

**Comment by metebalci** [comment]
There is an issue with TXT, that is why it is not shown when a TXT query is made. I am not sure how it affects the validation code yet, I will check. I did not check the code with TXT, so that is why I say TXT might not be working.

As I said, this tool is for normal/traditional internet users. However, as far as I understand there is [nothing wrong regarding to my site being on cloudflare](https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing), and onion routing on cloudflare is also enabled for my site. If you are shown a challange, that means your exit node has a bad score etc. Being said that, I am not actively trying to make it work for Tor users. You can just browse the site on public internet.

**Comment by metebalci** [comment]
TXT issue fixed with dcd4d8aa890b0601c19086e11178e7d7fe19619b

Also set -e added to bash script

**Comment by emdee-is** [comment]
> TXT issue fixed with dcd4d8a

Did you test it on ```metebalaci.com``` and does it pass signature verification?

Did you change the ordering in the bash script to top-down verification?
```
. -> .com -> metebalaci.com
```

Could you look at my ```validate_third_level_domain.sh``` and tell me if it works for you against ```www.metebalaci.com```?

**Comment by emdee-is** [comment]
The script assumes that the $rr produced a file
```
digsec validate $dest/$domain2.$domain1.IN.$rr
```
but if rr = TXT it may not have. So you get a false failure if rr=TXT and there was not text. So in my script, there's a 
```
if [ $rr = TXT -a ! -f $dest/$domain2.$domain1.IN.$rr ] ; then
```
so you don't get false failures.

Did the validate_third_level_domain.sh work? Could you include it if it does so we can test it against ```www,metebalci.com```?

**Comment by metebalci** [comment]
I did not check specifically what you describe but as I said it was not handling TXT at one level (there is an abstraction in the code, it was implemented at low level as it did not depend on record type but it was not implemented on higher level), so I am not surprised if it was not working.

I am working on a more flexible validate script.

**Comment by metebalci** [comment]
There was also an error in the validation script. If you do not add +cd flag (checking disabled) and if the DNS server is DNSSEC validating, then it would not return a record with wrong signature (returns an error). So this has to be added if the raw records are to be saved.

**Comment by emdee-is** [comment]
I'm not sure that I follow you as this is my first experience with DNSsec; I assume that I would want to to be validating and saving records. The best for me is if you could explain it by comments in the validate scripts so I can understand and follow the code with the explanation.

It would also be nice to have an example of 3rd level validation of say ```www.metebalci.com``` for TXT as that is my use case.

AFAIK this is the first time I've seen standalone validating DNSsec in Python so I feel it is a huge contribution.

**Comment by metebalci** [comment]
What you are asking is to describe you how DNSSEC works, which I cannot do just by writing comments, hence the need for blog posts. Even the blog posts are not totally enough, DNSSEC is not that simple.

3rd level validation is not same as up to 2nd level validation. I need to check RFCs to implement it properly.

In order to be able to write the validation script properly, I removed the bash script and added a python script with . I am going to work on that for 3rd (actually 2+) level validation.

**Comment by emdee-is** [comment]
I look forward to the Python script, but until it''s working, could you leave the bash script in so we can use it for testing? I have a bash testsuite testing both known good and known bad sites that uses your script.

What I was saying it very simple: if you ask for a TXT record from a site that doesn't have an TXT record, ans you ask to save, it seems digsec does not write an empty result file. So your bash script errors because it tries to access a file that is not there, So my suggestion was that in the case of TXT only,bash looks for  the existence of the .TXT file before trying to do anything with it.

**Comment by metebalci** [comment]
Like I said, for your own case and need, you should write your own script using digsec standalone, not using the scripts in the codebase. They are only an example, not meant to be used as it is.
I am not sure exactly what your point is with non-existent TXT (or any type) record. If you mean to authenticate the non-existence of a record, this is #16 . As I said, bash script was not a user application to be used in any way, it was just a demo, as the current python script. I should add a notice for this it seems.
